In [1]:
# pandas library import 
import pandas as pd

# dataframe creation 
df = pd.read_csv('data-final.csv', delimiter="\t")

# (note: specify path of dataset file if no compiled directory)
# df = pd.read_csv(r'/Users/.../data-final.csv', delimiter="\t")

In [2]:
df

EXT1  EXT2  EXT3  EXT4  EXT5  EXT6  EXT7  EXT8  EXT9  EXT10  ...  \
0         4.0   1.0   5.0   2.0   5.0   1.0   5.0   2.0   4.0    1.0  ...   
1         3.0   5.0   3.0   4.0   3.0   3.0   2.0   5.0   1.0    5.0  ...   
2         2.0   3.0   4.0   4.0   3.0   2.0   1.0   3.0   2.0    5.0  ...   
3         2.0   2.0   2.0   3.0   4.0   2.0   2.0   4.0   1.0    4.0  ...   
4         3.0   3.0   3.0   3.0   5.0   3.0   3.0   5.0   3.0    4.0  ...   
...       ...   ...   ...   ...   ...   ...   ...   ...   ...    ...  ...   
1015336   4.0   2.0   4.0   3.0   4.0   3.0   3.0   3.0   3.0    3.0  ...   
1015337   4.0   3.0   4.0   3.0   3.0   3.0   4.0   4.0   3.0    3.0  ...   
1015338   4.0   2.0   4.0   3.0   5.0   1.0   4.0   2.0   4.0    4.0  ...   
1015339   2.0   4.0   3.0   4.0   2.0   2.0   1.0   4.0   2.0    4.0  ...   
1015340   4.0   2.0   4.0   2.0   4.0   1.0   4.0   2.0   4.0    4.0  ...   

                    dateload  screenw  screenh  introelapse  testelapse  \
0        2016-03-03 02:01:01    768.0   1024.0          9.0       234.0   
1        2016-03-03 02:01:20   1360.0    768.0         12.0       179.0   
2        2016-03-03 02:01:56   1366.0    768.0          3.0       186.0   
3        2016-03-03 02:02:02   1920.0   1200.0        186.0       219.0   
4        2016-03-03 02:02:57   1366.0    768.0          8.0       315.0   
...                      ...      ...      ...          ...         ...   
1015336  2018-11-08 12:04:58   1920.0   1080.0          3.0       160.0   
1015337  2018-11-08 12:07:18   1920.0   1080.0          3.0       122.0   
1015338  2018-11-08 12:07:49   1920.0   1080.0          2.0       135.0   
1015339  2018-11-08 12:08:34   1920.0   1080.0          6.0       212.0   
1015340  2018-11-08 12:08:45   1920.0   1080.0          3.0       176.0   

         endelapse  IPC  country  lat_appx_lots_of_err  long_appx_lots_of_err  
0                6    1       GB               51.5448                 0.1991  
1               11    1       MY                3.1698                101.706  
2                7    1       GB               54.9119                -1.3833  
3                7    1       GB                 51.75                  -1.25  
4               17    2       KE                   1.0                   38.0  
...            ...  ...      ...                   ...                    ...  
1015336         10    2       US               39.9883               -75.2208  
1015337          7    1       US                  38.0                  -97.0  
1015338         12    6       US               36.1473                -86.777  
1015339          8    1       US               34.1067              -117.8067  
1015340          9    1       US                  38.0                  -97.0  

[1015341 rows x 110 columns]

In [3]:
# the 50 columns that represent the personality test questions (found in codebook.txt)
columns = df.columns

In [4]:
for column in columns:
    print(column)

EXT1
EXT2
EXT3
EXT4
EXT5
EXT6
EXT7
EXT8
EXT9
EXT10
EST1
EST2
EST3
EST4
EST5
EST6
EST7
EST8
EST9
EST10
AGR1
AGR2
AGR3
AGR4
AGR5
AGR6
AGR7
AGR8
AGR9
AGR10
CSN1
CSN2
CSN3
CSN4
CSN5
CSN6
CSN7
CSN8
CSN9
CSN10
OPN1
OPN2
OPN3
OPN4
OPN5
OPN6
OPN7
OPN8
OPN9
OPN10
EXT1_E
EXT2_E
EXT3_E
EXT4_E
EXT5_E
EXT6_E
EXT7_E
EXT8_E
EXT9_E
EXT10_E
EST1_E
EST2_E
EST3_E
EST4_E
EST5_E
EST6_E
EST7_E
EST8_E
EST9_E
EST10_E
AGR1_E
AGR2_E
AGR3_E
AGR4_E
AGR5_E
AGR6_E
AGR7_E
AGR8_E
AGR9_E
AGR10_E
CSN1_E
CSN2_E
CSN3_E
CSN4_E
CSN5_E
CSN6_E
CSN7_E
CSN8_E
CSN9_E
CSN10_E
OPN1_E
OPN2_E
OPN3_E
OPN4_E
OPN5_E
OPN6_E
OPN7_E
OPN8_E
OPN9_E
OPN10_E
dateload
screenw
screenh
introelapse
testelapse
endelapse
IPC
country
lat_appx_lots_of_err
long_appx_lots_of_err


In [5]:
# numpy library import
import numpy as np

In [14]:
# adjusts the dataframe from 110 columns to 50 (number of rows remains the same)
full_dataframe = df[df.columns[0:50]]

In [15]:
# displays the new setup of the dataframe's columns
pd.set_option('display.max_columns', None)

In [16]:
# outputs the complete dataframe
full_dataframe

EXT1  EXT2  EXT3  EXT4  EXT5  EXT6  EXT7  EXT8  EXT9  EXT10  EST1  \
0         4.0   1.0   5.0   2.0   5.0   1.0   5.0   2.0   4.0    1.0   1.0   
1         3.0   5.0   3.0   4.0   3.0   3.0   2.0   5.0   1.0    5.0   2.0   
2         2.0   3.0   4.0   4.0   3.0   2.0   1.0   3.0   2.0    5.0   4.0   
3         2.0   2.0   2.0   3.0   4.0   2.0   2.0   4.0   1.0    4.0   3.0   
4         3.0   3.0   3.0   3.0   5.0   3.0   3.0   5.0   3.0    4.0   1.0   
...       ...   ...   ...   ...   ...   ...   ...   ...   ...    ...   ...   
1015336   4.0   2.0   4.0   3.0   4.0   3.0   3.0   3.0   3.0    3.0   4.0   
1015337   4.0   3.0   4.0   3.0   3.0   3.0   4.0   4.0   3.0    3.0   4.0   
1015338   4.0   2.0   4.0   3.0   5.0   1.0   4.0   2.0   4.0    4.0   3.0   
1015339   2.0   4.0   3.0   4.0   2.0   2.0   1.0   4.0   2.0    4.0   4.0   
1015340   4.0   2.0   4.0   2.0   4.0   1.0   4.0   2.0   4.0    4.0   4.0   

         EST2  EST3  EST4  EST5  EST6  EST7  EST8  EST9  EST10  AGR1  AGR2  \
0         4.0   4.0   2.0   2.0   2.0   2.0   2.0   3.0    2.0   2.0   5.0   
1         3.0   4.0   1.0   3.0   1.0   2.0   1.0   3.0    1.0   1.0   4.0   
2         4.0   4.0   2.0   2.0   2.0   2.0   2.0   1.0    3.0   1.0   4.0   
3         3.0   3.0   2.0   3.0   2.0   2.0   2.0   4.0    3.0   2.0   4.0   
4         5.0   5.0   3.0   1.0   1.0   1.0   1.0   3.0    2.0   1.0   5.0   
...       ...   ...   ...   ...   ...   ...   ...   ...    ...   ...   ...   
1015336   3.0   3.0   3.0   4.0   3.0   4.0   3.0   3.0    3.0   5.0   4.0   
1015337   3.0   5.0   1.0   5.0   5.0   4.0   4.0   4.0    5.0   2.0   4.0   
1015338   2.0   4.0   3.0   2.0   2.0   4.0   2.0   4.0    1.0   3.0   5.0   
1015339   3.0   4.0   2.0   4.0   4.0   2.0   2.0   4.0    4.0   2.0   3.0   
1015340   3.0   4.0   3.0   2.0   3.0   3.0   1.0   4.0    2.0   1.0   5.0   

         AGR3  AGR4  AGR5  AGR6  AGR7  AGR8  AGR9  AGR10  CSN1  CSN2  CSN3  \
0         2.0   4.0   2.0   3.0   2.0   4.0   3.0    4.0   3.0   4.0   3.0   
1         1.0   5.0   1.0   5.0   3.0   4.0   5.0    3.0   3.0   2.0   5.0   
2         1.0   4.0   2.0   4.0   1.0   4.0   4.0    3.0   4.0   2.0   2.0   
3         3.0   4.0   2.0   4.0   2.0   4.0   3.0    4.0   2.0   4.0   4.0   
4         1.0   5.0   1.0   3.0   1.0   5.0   5.0    3.0   5.0   1.0   5.0   
...       ...   ...   ...   ...   ...   ...   ...    ...   ...   ...   ...   
1015336   2.0   5.0   2.0   4.0   2.0   4.0   4.0    4.0   2.0   3.0   3.0   
1015337   1.0   4.0   3.0   5.0   3.0   3.0   5.0    3.0   3.0   2.0   3.0   
1015338   5.0   3.0   2.0   3.0   2.0   4.0   3.0    5.0   4.0   5.0   3.0   
1015339   2.0   4.0   3.0   4.0   2.0   4.0   4.0    3.0   4.0   2.0   4.0   
1015340   2.0   4.0   3.0   5.0   2.0   3.0   4.0    5.0   3.0   4.0   3.0   

         CSN4  CSN5  CSN6  CSN7  CSN8  CSN9  CSN10  OPN1  OPN2  OPN3  OPN4  \
0         2.0   2.0   4.0   4.0   2.0   4.0    4.0   5.0   1.0   4.0   1.0   
1         3.0   3.0   1.0   3.0   3.0   5.0    3.0   1.0   2.0   4.0   2.0   
2         2.0   3.0   3.0   4.0   2.0   4.0    2.0   5.0   1.0   2.0   1.0   
3         4.0   1.0   2.0   2.0   3.0   1.0    4.0   4.0   2.0   5.0   2.0   
4         1.0   3.0   1.0   5.0   1.0   5.0    5.0   5.0   1.0   5.0   1.0   
...       ...   ...   ...   ...   ...   ...    ...   ...   ...   ...   ...   
1015336   3.0   4.0   4.0   4.0   2.0   3.0    3.0   2.0   2.0   4.0   3.0   
1015337   4.0   3.0   3.0   2.0   3.0   2.0    3.0   4.0   1.0   5.0   1.0   
1015338   5.0   1.0   5.0   1.0   4.0   1.0    4.0   5.0   1.0   5.0   1.0   
1015339   2.0   2.0   2.0   4.0   2.0   4.0    4.0   5.0   2.0   4.0   2.0   
1015340   3.0   2.0   3.0   3.0   2.0   2.0    3.0   5.0   1.0   5.0   1.0   

         OPN5  OPN6  OPN7  OPN8  OPN9  OPN10  
0         4.0   1.0   5.0   3.0   4.0    5.0  
1         3.0   1.0   4.0   2.0   5.0    3.0  
2         4.0   2.0   5.0   3.0   4.0    4.0  
3         3.0   1.0   4.0   4.0   3.0    3.0  
4         5.0   1.0   5.0 

In [17]:
# fills in any empty values in the dataframe's columns with a zero
full_dataframe = full_dataframe.fillna(0)

In [18]:
# the mini batch k-means algorithm (fro a scalar library)
from sklearn.cluster import MiniBatchKMeans

In [19]:
# kmeans parameters
# n_clusters = number of personality types (10)
# batch_size = number of data rows fed into the kmeans algorithm/per iteration 
(10,000 total batches out of 1,000,000 total rows)
# max_iter = iterates through all the batches 100 times

kmeans = MiniBatchKMeans(n_clusters = 10, random_state = 0, batch_size = 100, max_iter = 100).fit(full_dataframe)

In [20]:
# double checking that the total number of clusters matches our kmeans parameter
len(kmeans.cluster_centers_)

10

In [42]:
# implementing KMeans Clustering on the 10 clusters

In [21]:
cluster_one = kmeans.cluster_centers_[0]

In [22]:
cluster_two = kmeans.cluster_centers_[1]

In [23]:
cluster_three = kmeans.cluster_centers_[2]

In [24]:
cluster_four = kmeans.cluster_centers_[3]

In [25]:
cluster_five = kmeans.cluster_centers_[4]

In [26]:
cluster_six = kmeans.cluster_centers_[5]

In [27]:
cluster_seven = kmeans.cluster_centers_[6]

In [28]:
cluster_eight = kmeans.cluster_centers_[7]

In [29]:
cluster_nine = kmeans.cluster_centers_[8]

In [30]:
cluster_ten = kmeans.cluster_centers_[9]

In [41]:
# outputs the KMeans Clustering on the 10 clusters, each array will represent that
# cluster's Personality Type typical answer score for all 50 questions

In [31]:
cluster_one

array([3.51875306, 1.8936703 , 4.45234737, 2.11922512, 4.35885553,
       1.56325379, 3.98647132, 2.76422671, 3.81405256, 2.3716646 ,
       2.05604329, 3.97875709, 2.92127457, 3.4824271 , 1.8897844 ,
       1.67228923, 1.87329092, 1.47554762, 1.86143174, 1.5434501 ,
       1.79666676, 4.49912207, 1.70769408, 4.29999136, 1.7910538 ,
       3.85187531, 1.50729685, 4.16565441, 4.14265565, 4.31282922,
       3.87432716, 2.42716099, 4.31288679, 1.68691172, 3.30911603,
       2.07210501, 3.97875709, 1.76252842, 3.69278374, 4.00077718,
       4.0497395 , 1.58055324, 4.18154342, 1.64966466, 4.2821738 ,
       1.53360583, 4.44892202, 3.33657638, 4.18433551, 4.42462796])

In [32]:
cluster_two

array([1.48116676, 4.02453419, 2.02357631, 4.39140376, 1.97410623,
       3.29533727, 1.44507617, 4.41009795, 1.77628774, 4.68572135,
       4.16827859, 2.48407132, 4.53635324, 1.91178197, 3.32849241,
       3.57843834, 3.6944659 , 3.41596885, 3.72026697, 3.97790687,
       2.10348237, 3.41139573, 2.25572413, 4.05493928, 2.36856904,
       3.94787257, 2.58226988, 3.53233631, 3.83889009, 3.06244786,
       2.97222136, 3.2692272 , 4.01968297, 3.27590149, 2.1016284 ,
       3.30352563, 3.66257763, 2.86092142, 2.84117665, 3.48635788,
       3.88962704, 1.94685289, 4.33640268, 1.75360751, 3.6229954 ,
       1.73877576, 3.92559404, 3.48592529, 4.51741186, 4.01288508])

In [33]:
cluster_three

array([0.83021807, 0.65420561, 0.54672897, 0.38369678, 0.2933541 ,
       0.17705088, 0.13862928, 0.13032191, 0.14485981, 0.16770509,
       0.75233645, 0.5529595 , 0.5046729 , 0.30218069, 0.21079958,
       0.13136033, 0.11007269, 0.12201454, 0.14537902, 0.16303219,
       0.73727934, 0.72533749, 0.38110073, 0.41277259, 0.22897196,
       0.19418484, 0.11370717, 0.13291796, 0.15160955, 0.14330218,
       0.79023884, 0.56074766, 0.54932503, 0.30477674, 0.20560748,
       0.13603323, 0.12253375, 0.11682243, 0.14953271, 0.192108  ,
       0.69574247, 0.4854621 , 0.45482866, 0.26012461, 0.21858775,
       0.12045691, 0.13343718, 0.13239875, 0.15212876, 0.24091381])

In [34]:
cluster_four

array([3.43633717, 2.11564992, 3.9493735 , 2.44801291, 3.9587394 ,
       2.10783445, 3.60868877, 2.87245285, 3.52101   , 2.86666245,
       3.29787369, 3.15105683, 3.80904316, 2.76585242, 2.92190862,
       2.85229718, 3.02680041, 2.5958423 , 3.20155676, 2.31980129,
       2.69443741, 3.94598785, 2.29866473, 3.79002658, 2.35115808,
       3.61808632, 2.09002025, 3.67542083, 3.71190356, 3.71291609,
       3.70665106, 2.23867232, 3.99601316, 2.11239084, 3.31252373,
       2.13643843, 3.96070118, 2.26604227, 3.77183268, 3.6715922 ,
       3.13488799, 2.58508417, 3.51227693, 2.54888622, 3.67886976,
       2.25405012, 3.78803316, 2.65191115, 3.64140615, 3.70456271])

In [35]:
cluster_five

array([2.13030631, 3.22436219, 3.22019365, 3.61747091, 3.10785426,
       2.46803683, 2.26657521, 4.01807245, 2.36403451, 4.08585072,
       3.33907606, 3.17605467, 4.10273593, 2.67883809, 2.60628446,
       2.54937604, 2.62427776, 2.15608263, 2.73374139, 2.51447115,
       1.64818088, 4.10112656, 1.57660344, 4.46938237, 1.82333852,
       4.19140965, 1.82779727, 4.10094188, 4.29082131, 3.86001108,
       3.93755112, 2.17613382, 4.41846292, 1.86330897, 3.31287761,
       1.94955544, 4.2356014 , 1.84220246, 3.88562911, 4.02071076,
       3.86151492, 1.83993351, 4.10885682, 1.80370947, 3.92955703,
       1.71614384, 4.18753133, 3.23488906, 4.42307997, 4.05456033])

In [36]:
cluster_six

array([2.88937956, 2.32378089, 3.22794325, 3.09001221, 3.6427699 ,
       2.02680948, 3.02173573, 3.28196937, 3.25666322, 3.68110495,
       4.43693821, 2.35372232, 4.68743149, 2.06414232, 3.71812459,
       4.14369382, 4.30267155, 4.10072348, 4.14447681, 3.94378152,
       1.8712769 , 4.25472141, 2.53922766, 4.46932256, 1.81900467,
       4.32578534, 1.84127282, 4.04510007, 4.42704125, 3.79767609,
       3.09781077, 3.46988631, 4.1105578 , 3.37880923, 2.31404053,
       3.4165179 , 3.77741238, 2.8217921 , 3.15872718, 3.65254158,
       3.91427856, 2.06213787, 4.44708572, 1.83256601, 3.96573648,
       1.65523505, 4.00538695, 3.56929437, 4.51758589, 4.28572771])

In [37]:
cluster_seven

array([3.59374497, 1.76441715, 4.12931173, 2.261869  , 4.19829945,
       1.68563918, 3.9018293 , 2.6257175 , 3.8923341 , 2.64857036,
       3.18893836, 3.43109275, 3.84056649, 2.67603669, 2.82243442,
       2.75181053, 3.16780216, 2.68853602, 2.93769111, 2.56008261,
       1.83265383, 4.49120219, 2.35628453, 4.35464836, 1.77149831,
       4.05109704, 1.59189421, 4.04034118, 4.23609248, 4.04782469,
       2.74191299, 3.9467035 , 3.65672442, 3.19580495, 1.98487206,
       3.80038625, 3.13432756, 2.76428303, 2.65790462, 3.34252454,
       3.8028271 , 1.90464567, 4.29266134, 1.78954992, 4.01461831,
       1.64409098, 4.0398852 , 3.35620407, 4.15262057, 4.27911593])

In [38]:
cluster_eight

array([2.17928221, 3.36957675, 2.6700942 , 3.63155101, 2.5923776 ,
       3.38184954, 2.12518243, 3.74326655, 2.42719252, 4.15918137,
       3.99625182, 2.73776038, 4.21629959, 2.65719119, 3.58202866,
       3.72960064, 3.77636991, 3.49767812, 3.85710495, 3.34423511,
       2.88785326, 3.23404538, 2.52567334, 3.62873159, 2.73122595,
       3.77202468, 2.8175335 , 3.35819955, 3.48096059, 3.09788377,
       2.90921454, 2.94404272, 3.49469285, 3.13659281, 2.50928751,
       3.21649861, 3.50918801, 2.91770598, 3.03943877, 3.1310203 ,
       2.61546371, 3.2365331 , 3.27185883, 2.94682898, 2.91156959,
       2.88825129, 3.16485339, 2.31408385, 3.68110654, 2.92579939])

In [39]:
cluster_nine

array([1.89171773, 3.74429844, 2.82029819, 3.79866069, 2.40514246,
       3.17073094, 1.89178091, 3.97997347, 2.35476025, 4.17351065,
       2.19862278, 3.91019647, 3.01203487, 3.18823046, 2.20219218,
       1.81815023, 2.01402489, 1.61548424, 2.2772443 , 2.06510203,
       2.72780972, 3.10297555, 2.15582159, 3.22793607, 2.98537494,
       3.07780024, 2.91354476, 3.18175501, 2.97801504, 3.18314486,
       3.41913576, 2.62540274, 3.90946996, 2.15042011, 2.64530293,
       2.49946301, 3.69751722, 2.31789753, 3.11718997, 3.55916356,
       3.52997663, 2.02056352, 3.60139617, 2.12897214, 3.65102028,
       2.15951734, 4.04804473, 2.99121865, 3.8816097 , 3.64088066])

In [40]:
cluster_ten

array([2.59113193, 2.82211328, 2.80578657, 3.20997111, 3.04797339,
       2.24879629, 2.4862558 , 3.20992734, 3.32959818, 3.73260089,
       3.10702092, 3.24183665, 3.63779217, 2.5325221 , 2.79755756,
       2.82080014, 3.3772214 , 3.01667688, 3.56552569, 3.11152937,
       3.37744025, 3.06898363, 3.48831305, 2.58172109, 3.47535674,
       2.50590913, 3.22791736, 2.7660422 , 2.53260965, 3.0155826 ,
       2.9187604 , 3.53024599, 3.83730193, 3.15249934, 2.00240742,
       3.48279786, 3.31983717, 3.05834719, 2.49483498, 3.45408387,
       4.18970498, 1.69101812, 4.34237941, 1.73921037, 4.17644227,
       1.6324083 , 4.27203887, 3.91919811, 4.1898363 , 4.37043684])

In [48]:
# to make this data more comprehensible, we'll compile the 50 scores into the 
# 5 Factor Model (FFM) of each Personality Cluster Type.

# NOTE: the subtraction and addition of specific questions follows the following logic:

# subtraction: if a True (+1) answer to this question deters from one of the FFM traits
# ie. if person does not talk a lot, extroversion score specifically decreases

# addition: if a True (+1) answer to this question compliments one of the FFM traits
# ie. if person is the life of the party, extroversion score specifically increases

In [54]:
cluster_one_scores = {}

# EXTROVERSION SCORE
cluster_one_scores['extroversion_score'] =  cluster_one[0] - cluster_one[1] + cluster_one[2] - cluster_one[3] + cluster_one[4] - cluster_one[5] + cluster_one[6] - cluster_one[7] + cluster_one[8] - cluster_one[9]

# NEUROTICISM SCORE
cluster_one_scores['neuroticism_score'] =  cluster_one[0] - cluster_one[1] + cluster_one[2] - cluster_one[3] + cluster_one[4] + cluster_one[5] + cluster_one[6] + cluster_one[7] + cluster_one[8] + cluster_one[9]

# AGREEABLENESS SCORE
cluster_one_scores['agreeableness_score'] =  -cluster_one[0] + cluster_one[1] - cluster_one[2] + cluster_one[3] - cluster_one[4] - cluster_one[5] + cluster_one[6] - cluster_one[7] + cluster_one[8] + cluster_one[9]

# CONSCIENTIOUSNESS SCORE
cluster_one_scores['conscientiousness_score'] =  cluster_one[0] - cluster_one[1] + cluster_one[2] - cluster_one[3] + cluster_one[4] - cluster_one[5] + cluster_one[6] - cluster_one[7] + cluster_one[8] + cluster_one[9]

# OPENNESS SCORE
cluster_one_scores['openness_score'] =  cluster_one[0] - cluster_one[1] + cluster_one[2] - cluster_one[3] + cluster_one[4] - cluster_one[5] + cluster_one[6] + cluster_one[7] + cluster_one[8] + cluster_one[9]


In [55]:
cluster_one_scores

{'extroversion_score': 9.418439308022236,
 'neuroticism_score': 22.81672951267956,
 'agreeableness_score': -2.472352551740031,
 'conscientiousness_score': 14.16176851558679,
 'openness_score': 19.690221927981366}

In [56]:
cluster_two_scores = {}

# EXTROVERSION SCORE
cluster_two_scores['extroversion_score'] =  cluster_two[0] - cluster_two[1] + cluster_two[2] - cluster_two[3] + cluster_two[4] - cluster_two[5] + cluster_two[6] - cluster_two[7] + cluster_two[8] - cluster_two[9]

# NEUROTICISM SCORE
cluster_two_scores['neuroticism_score'] =  cluster_two[0] - cluster_two[1] + cluster_two[2] - cluster_two[3] + cluster_two[4] + cluster_two[5] + cluster_two[6] + cluster_two[7] + cluster_two[8] + cluster_two[9]

# AGREEABLENESS SCORE
cluster_two_scores['agreeableness_score'] =  -cluster_two[0] + cluster_two[1] - cluster_two[2] + cluster_two[3] - cluster_two[4] - cluster_two[5] + cluster_two[6] - cluster_two[7] + cluster_two[8] + cluster_two[9]

# CONSCIENTIOUSNESS SCORE
cluster_two_scores['conscientiousness_score'] =  cluster_two[0] - cluster_two[1] + cluster_two[2] - cluster_two[3] + cluster_two[4] - cluster_two[5] + cluster_two[6] - cluster_two[7] + cluster_two[8] + cluster_two[9]

# OPENNESS SCORE
cluster_two_scores['openness_score'] =  cluster_two[0] - cluster_two[1] + cluster_two[2] - cluster_two[3] + cluster_two[4] - cluster_two[5] + cluster_two[6] + cluster_two[7] + cluster_two[8] + cluster_two[9]


In [57]:
cluster_two_scores

{'extroversion_score': -12.106881315082008,
 'neuroticism_score': 12.675431820288606,
 'agreeableness_score': 3.1387386830639694,
 'conscientiousness_score': -2.735438618175065,
 'openness_score': 6.084757284553353}

In [58]:
cluster_three_scores = {}

# EXTROVERSION SCORE
cluster_three_scores['extroversion_score'] =  cluster_three[0] - cluster_three[1] + cluster_three[2] - cluster_three[3] + cluster_three[4] - cluster_three[5] + cluster_three[6] - cluster_three[7] + cluster_three[8] - cluster_three[9]

# NEUROTICISM SCORE
cluster_three_scores['neuroticism_score'] =  cluster_three[0] - cluster_three[1] + cluster_three[2] - cluster_three[3] + cluster_three[4] + cluster_three[5] + cluster_three[6] + cluster_three[7] + cluster_three[8] + cluster_three[9]

# AGREEABLENESS SCORE
cluster_three_scores['agreeableness_score'] =  -cluster_three[0] + cluster_three[1] - cluster_three[2] + cluster_three[3] - cluster_three[4] - cluster_three[5] + cluster_three[6] - cluster_three[7] + cluster_three[8] + cluster_three[9]

# CONSCIENTIOUSNESS SCORE
cluster_three_scores['conscientiousness_score'] =  cluster_three[0] - cluster_three[1] + cluster_three[2] - cluster_three[3] + cluster_three[4] - cluster_three[5] + cluster_three[6] - cluster_three[7] + cluster_three[8] + cluster_three[9]

# OPENNESS SCORE
cluster_three_scores['openness_score'] =  cluster_three[0] - cluster_three[1] + cluster_three[2] - cluster_three[3] + cluster_three[4] - cluster_three[5] + cluster_three[6] + cluster_three[7] + cluster_three[8] + cluster_three[9]


In [59]:
cluster_three_scores

{'extroversion_score': 0.4408099688473518,
 'neuroticism_score': 1.3909657320872277,
 'agreeableness_score': -0.4885773624091373,
 'conscientiousness_score': 0.776220145379024,
 'openness_score': 1.036863966770509}

In [60]:
cluster_four_scores = {}

# EXTROVERSION SCORE
cluster_four_scores['extroversion_score'] =  cluster_four[0] - cluster_four[1] + cluster_four[2] - cluster_four[3] + cluster_four[4] - cluster_four[5] + cluster_four[6] - cluster_four[7] + cluster_four[8] - cluster_four[9]

# NEUROTICISM SCORE
cluster_four_scores['neuroticism_score'] =  cluster_four[0] - cluster_four[1] + cluster_four[2] - cluster_four[3] + cluster_four[4] + cluster_four[5] + cluster_four[6] + cluster_four[7] + cluster_four[8] + cluster_four[9]

# AGREEABLENESS SCORE
cluster_four_scores['agreeableness_score'] =  -cluster_four[0] + cluster_four[1] - cluster_four[2] + cluster_four[3] - cluster_four[4] - cluster_four[5] + cluster_four[6] - cluster_four[7] + cluster_four[8] + cluster_four[9]

# CONSCIENTIOUSNESS SCORE
cluster_four_scores['conscientiousness_score'] =  cluster_four[0] - cluster_four[1] + cluster_four[2] - cluster_four[3] + cluster_four[4] - cluster_four[5] + cluster_four[6] - cluster_four[7] + cluster_four[8] + cluster_four[9]

# OPENNESS SCORE
cluster_four_scores['openness_score'] =  cluster_four[0] - cluster_four[1] + cluster_four[2] - cluster_four[3] + cluster_four[4] - cluster_four[5] + cluster_four[6] + cluster_four[7] + cluster_four[8] + cluster_four[9]


In [61]:
cluster_four_scores

{'extroversion_score': 6.063536261232744,
 'neuroticism_score': 21.75743576762436,
 'agreeableness_score': -1.7647133274269127,
 'conscientiousness_score': 11.796861156815591,
 'openness_score': 17.5417668649538}

In [62]:
cluster_five_scores = {}

# EXTROVERSION SCORE
cluster_five_scores['extroversion_score'] =  cluster_five[0] - cluster_five[1] + cluster_five[2] - cluster_five[3] + cluster_five[4] - cluster_five[5] + cluster_five[6] - cluster_five[7] + cluster_five[8] - cluster_five[9]

# NEUROTICISM SCORE
cluster_five_scores['neuroticism_score'] =  cluster_five[0] - cluster_five[1] + cluster_five[2] - cluster_five[3] + cluster_five[4] + cluster_five[5] + cluster_five[6] + cluster_five[7] + cluster_five[8] + cluster_five[9]

# AGREEABLENESS SCORE
cluster_five_scores['agreeableness_score'] =  -cluster_five[0] + cluster_five[1] - cluster_five[2] + cluster_five[3] - cluster_five[4] - cluster_five[5] + cluster_five[6] - cluster_five[7] + cluster_five[8] + cluster_five[9]

# CONSCIENTIOUSNESS SCORE
cluster_five_scores['conscientiousness_score'] =  cluster_five[0] - cluster_five[1] + cluster_five[2] - cluster_five[3] + cluster_five[4] - cluster_five[5] + cluster_five[6] - cluster_five[7] + cluster_five[8] + cluster_five[9]

# OPENNESS SCORE
cluster_five_scores['openness_score'] =  cluster_five[0] - cluster_five[1] + cluster_five[2] - cluster_five[3] + cluster_five[4] - cluster_five[5] + cluster_five[6] + cluster_five[7] + cluster_five[8] + cluster_five[9]


In [63]:
cluster_five_scores

{'extroversion_score': -4.32482916919505,
 'neuroticism_score': 16.819090837136894,
 'agreeableness_score': 0.6138300398385099,
 'conscientiousness_score': 3.8468722792390917,
 'openness_score': 11.883017175421466}

In [64]:
cluster_six_scores = {}

# EXTROVERSION SCORE
cluster_six_scores['extroversion_score'] =  cluster_six[0] - cluster_six[1] + cluster_six[2] - cluster_six[3] + cluster_six[4] - cluster_six[5] + cluster_six[6] - cluster_six[7] + cluster_six[8] - cluster_six[9]

# NEUROTICISM SCORE
cluster_six_scores['neuroticism_score'] =  cluster_six[0] - cluster_six[1] + cluster_six[2] - cluster_six[3] + cluster_six[4] + cluster_six[5] + cluster_six[6] + cluster_six[7] + cluster_six[8] + cluster_six[9]

# AGREEABLENESS SCORE
cluster_six_scores['agreeableness_score'] =  -cluster_six[0] + cluster_six[1] - cluster_six[2] + cluster_six[3] - cluster_six[4] - cluster_six[5] + cluster_six[6] - cluster_six[7] + cluster_six[8] + cluster_six[9]

# CONSCIENTIOUSNESS SCORE
cluster_six_scores['conscientiousness_score'] =  cluster_six[0] - cluster_six[1] + cluster_six[2] - cluster_six[3] + cluster_six[4] - cluster_six[5] + cluster_six[6] - cluster_six[7] + cluster_six[8] + cluster_six[9]

# OPENNESS SCORE
cluster_six_scores['openness_score'] =  cluster_six[0] - cluster_six[1] + cluster_six[2] - cluster_six[3] + cluster_six[4] - cluster_six[5] + cluster_six[6] + cluster_six[7] + cluster_six[8] + cluster_six[9]


In [65]:
cluster_six_scores

{'extroversion_score': 1.6348147452159485,
 'neuroticism_score': 19.614582354599264,
 'agreeableness_score': 0.3044254439537828,
 'conscientiousness_score': 8.997024648438725,
 'openness_score': 15.560963387516054}

In [66]:
cluster_seven_scores = {}

# EXTROVERSION SCORE
cluster_seven_scores['extroversion_score'] =  cluster_seven[0] - cluster_seven[1] + cluster_seven[2] - cluster_seven[3] + cluster_seven[4] - cluster_seven[5] + cluster_seven[6] - cluster_seven[7] + cluster_seven[8] - cluster_seven[9]

# NEUROTICISM SCORE
cluster_seven_scores['neuroticism_score'] =  cluster_seven[0] - cluster_seven[1] + cluster_seven[2] - cluster_seven[3] + cluster_seven[4] + cluster_seven[5] + cluster_seven[6] + cluster_seven[7] + cluster_seven[8] + cluster_seven[9]

# AGREEABLENESS SCORE
cluster_seven_scores['agreeableness_score'] =  -cluster_seven[0] + cluster_seven[1] - cluster_seven[2] + cluster_seven[3] - cluster_seven[4] - cluster_seven[5] + cluster_seven[6] - cluster_seven[7] + cluster_seven[8] + cluster_seven[9]

# CONSCIENTIOUSNESS SCORE
cluster_seven_scores['conscientiousness_score'] =  cluster_seven[0] - cluster_seven[1] + cluster_seven[2] - cluster_seven[3] + cluster_seven[4] - cluster_seven[5] + cluster_seven[6] - cluster_seven[7] + cluster_seven[8] + cluster_seven[9]

# OPENNESS SCORE
cluster_seven_scores['openness_score'] =  cluster_seven[0] - cluster_seven[1] + cluster_seven[2] - cluster_seven[3] + cluster_seven[4] - cluster_seven[5] + cluster_seven[6] + cluster_seven[7] + cluster_seven[8] + cluster_seven[9]


In [67]:
cluster_seven_scores

{'extroversion_score': 8.72930636768416,
 'neuroticism_score': 22.649160452765436,
 'agreeableness_score': -1.7636929349284136,
 'conscientiousness_score': 14.026447079019384,
 'openness_score': 19.277882087870847}

In [68]:
cluster_eight_scores = {}

# EXTROVERSION SCORE
cluster_eight_scores['extroversion_score'] =  cluster_eight[0] - cluster_eight[1] + cluster_eight[2] - cluster_eight[3] + cluster_eight[4] - cluster_eight[5] + cluster_eight[6] - cluster_eight[7] + cluster_eight[8] - cluster_eight[9]

# NEUROTICISM SCORE
cluster_eight_scores['neuroticism_score'] =  cluster_eight[0] - cluster_eight[1] + cluster_eight[2] - cluster_eight[3] + cluster_eight[4] + cluster_eight[5] + cluster_eight[6] + cluster_eight[7] + cluster_eight[8] + cluster_eight[9]

# AGREEABLENESS SCORE
cluster_eight_scores['agreeableness_score'] =  -cluster_eight[0] + cluster_eight[1] - cluster_eight[2] + cluster_eight[3] - cluster_eight[4] - cluster_eight[5] + cluster_eight[6] - cluster_eight[7] + cluster_eight[8] + cluster_eight[9]

# CONSCIENTIOUSNESS SCORE
cluster_eight_scores['conscientiousness_score'] =  cluster_eight[0] - cluster_eight[1] + cluster_eight[2] - cluster_eight[3] + cluster_eight[4] - cluster_eight[5] + cluster_eight[6] - cluster_eight[7] + cluster_eight[8] + cluster_eight[9]

# OPENNESS SCORE
cluster_eight_scores['openness_score'] =  cluster_eight[0] - cluster_eight[1] + cluster_eight[2] - cluster_eight[3] + cluster_eight[4] - cluster_eight[5] + cluster_eight[6] + cluster_eight[7] + cluster_eight[8] + cluster_eight[9]


In [69]:
cluster_eight_scores

{'extroversion_score': -6.291296271726161,
 'neuroticism_score': 16.277298659944307,
 'agreeableness_score': 1.145813984343937,
 'conscientiousness_score': 2.02706647207115,
 'openness_score': 9.513599575427923}

In [70]:
cluster_nine_scores = {}

# EXTROVERSION SCORE
cluster_nine_scores['extroversion_score'] =  cluster_nine[0] - cluster_nine[1] + cluster_nine[2] - cluster_nine[3] + cluster_nine[4] - cluster_nine[5] + cluster_nine[6] - cluster_nine[7] + cluster_nine[8] - cluster_nine[9]

# NEUROTICISM SCORE
cluster_nine_scores['neuroticism_score'] =  cluster_nine[0] - cluster_nine[1] + cluster_nine[2] - cluster_nine[3] + cluster_nine[4] + cluster_nine[5] + cluster_nine[6] + cluster_nine[7] + cluster_nine[8] + cluster_nine[9]

# AGREEABLENESS SCORE
cluster_nine_scores['agreeableness_score'] =  -cluster_nine[0] + cluster_nine[1] - cluster_nine[2] + cluster_nine[3] - cluster_nine[4] - cluster_nine[5] + cluster_nine[6] - cluster_nine[7] + cluster_nine[8] + cluster_nine[9]

# CONSCIENTIOUSNESS SCORE
cluster_nine_scores['conscientiousness_score'] =  cluster_nine[0] - cluster_nine[1] + cluster_nine[2] - cluster_nine[3] + cluster_nine[4] - cluster_nine[5] + cluster_nine[6] - cluster_nine[7] + cluster_nine[8] + cluster_nine[9]

# OPENNESS SCORE
cluster_nine_scores['openness_score'] =  cluster_nine[0] - cluster_nine[1] + cluster_nine[2] - cluster_nine[3] + cluster_nine[4] - cluster_nine[5] + cluster_nine[6] + cluster_nine[7] + cluster_nine[8] + cluster_nine[9]


In [71]:
cluster_nine_scores

{'extroversion_score': -7.503474635163293,
 'neuroticism_score': 15.144955461494725,
 'agreeableness_score': 1.6951481458083189,
 'conscientiousness_score': 0.8435466548739594,
 'openness_score': 8.80349358771874}

In [72]:
cluster_ten_scores = {}

# EXTROVERSION SCORE
cluster_ten_scores['extroversion_score'] =  cluster_ten[0] - cluster_ten[1] + cluster_ten[2] - cluster_ten[3] + cluster_ten[4] - cluster_ten[5] + cluster_ten[6] - cluster_ten[7] + cluster_ten[8] - cluster_ten[9]

# NEUROTICISM SCORE
cluster_ten_scores['neuroticism_score'] =  cluster_ten[0] - cluster_ten[1] + cluster_ten[2] - cluster_ten[3] + cluster_ten[4] + cluster_ten[5] + cluster_ten[6] + cluster_ten[7] + cluster_ten[8] + cluster_ten[9]

# AGREEABLENESS SCORE
cluster_ten_scores['agreeableness_score'] =  -cluster_ten[0] + cluster_ten[1] - cluster_ten[2] + cluster_ten[3] - cluster_ten[4] - cluster_ten[5] + cluster_ten[6] - cluster_ten[7] + cluster_ten[8] + cluster_ten[9]

# CONSCIENTIOUSNESS SCORE
cluster_ten_scores['conscientiousness_score'] =  cluster_ten[0] - cluster_ten[1] + cluster_ten[2] - cluster_ten[3] + cluster_ten[4] - cluster_ten[5] + cluster_ten[6] - cluster_ten[7] + cluster_ten[8] + cluster_ten[9]

# OPENNESS SCORE
cluster_ten_scores['openness_score'] =  cluster_ten[0] - cluster_ten[1] + cluster_ten[2] - cluster_ten[3] + cluster_ten[4] - cluster_ten[5] + cluster_ten[6] + cluster_ten[7] + cluster_ten[8] + cluster_ten[9]


In [73]:
cluster_ten_scores

{'extroversion_score': -0.9626630482359997,
 'neuroticism_score': 17.41998599317168,
 'agreeableness_score': 1.6769237503282786,
 'conscientiousness_score': 6.502538737634612,
 'openness_score': 12.922393416790703}

In [74]:
# Instead of manually calculating each cluster's Personality Type's FFM scores, we can automate it as follows:

In [75]:
# dictionary of clusters/personality types
all_personality_types = {'cluster_one':cluster_one, 'cluster_two': cluster_two, 'cluster_three' :cluster_three, 'cluster_four':cluster_four, 'cluster_five':cluster_five, 
'cluster_six': cluster_six, 'cluster_seven': cluster_seven, 'cluster_eight': cluster_eight, 'cluster_nine': cluster_nine, 'cluster_ten': cluster_ten}

all_personality_types_scores ={}

for name, personality_type in all_personality_types.items():
    personality_trait = {}
    # PERSONALITY TRAIT'S SCORES
    personality_trait['extroversion_score'] =  personality_type[0] - personality_type[1] +personality_type[2] - personality_type[3] + personality_type[4] - personality_type[5] +personality_type[6] - personality_type[7] + personality_type[8] -personality_type[9]
    personality_trait['neuroticism_score'] =  personality_type[0] - personality_type[1] + personality_type[2] -personality_type[3] + personality_type[4] + personality_type[5] + personality_type[6] + personality_type[7] + personality_type[8] + personality_type[9]
    personality_trait['agreeableness_score'] =  -personality_type[0] +personality_type[1] - personality_type[2] + personality_type[3] - personality_type[4] - personality_type[5] + personality_type[6] - personality_type[7] + personality_type[8] + personality_type[9]
    personality_trait['conscientiousness_score'] = personality_type[0] - personality_type[1] + personality_type[2] -personality_type[3] +personality_type[4] - personality_type[5] +personality_type[6] -personality_type[7] + personality_type[8] + personality_type[9]
    personality_trait['openness_score'] =  personality_type[0] -personality_type[1] + personality_type[2] - personality_type[3] + personality_type[4] - personality_type[5] +personality_type[6] + personality_type[7] + personality_type[8] + personality_type[9]
    
    # initiates key-value pairs of cluster & scores
    all_personality_types_scores[name] = personality_trait
    

In [76]:
all_personality_types_scores

{'cluster_one': {'extroversion_score': 9.418439308022236,
  'neuroticism_score': 22.81672951267956,
  'agreeableness_score': -2.472352551740031,
  'conscientiousness_score': 14.16176851558679,
  'openness_score': 19.690221927981366},
 'cluster_two': {'extroversion_score': -12.106881315082008,
  'neuroticism_score': 12.675431820288606,
  'agreeableness_score': 3.1387386830639694,
  'conscientiousness_score': -2.735438618175065,
  'openness_score': 6.084757284553353},
 'cluster_three': {'extroversion_score': 0.4408099688473518,
  'neuroticism_score': 1.3909657320872277,
  'agreeableness_score': -0.4885773624091373,
  'conscientiousness_score': 0.776220145379024,
  'openness_score': 1.036863966770509},
 'cluster_four': {'extroversion_score': 6.063536261232744,
  'neuroticism_score': 21.75743576762436,
  'agreeableness_score': -1.7647133274269127,
  'conscientiousness_score': 11.796861156815591,
  'openness_score': 17.5417668649538},
 'cluster_five': {'extroversion_score': -4.3248291691950

In [ ]:
# Lastly, we normalize all of these clusters' data scores to make them relative to each other & thus, yield 
# an informative comparison between all of the Personality Types with each type being guided by the FFM.
# MIN-MAX NORMALIZATION EQUATION IS USED [v’=(v-min)/(max-min)]